### PR TITLE
more linux standard. Should have been this from start

### PR DESCRIPTION
**Pull request by Natherul**
## Proposed Changes

  - changed --updateonly to --update-only
  - changed --setlocation to --set-location

### CODE REVIEW

**Comment by Natherul** [comment]
maybe we should even change --update-only to --update-all

**Comment by Idrinth** [comment]
not going to break backwards compatibility, but I'm fine with adding more aliases that sound more sensible

**Comment by Natherul** [comment]
Backwards compability? Its not like this is a component that is a dependency for something else, it's only how someone interfaces with it.

And if you mean the wrapper then your changes made major parts of it already obsolete by adding short form commands. Don't get me wrong the wrapper is still a good addition to get rid off the prefix java -jar.

In addition to this the cli commands have only been out for a very limited time so it's not like someone has trained behavior of using it. If something can clearly be improved and follow a standard I think we should.

**Comment by Natherul** [comment]
My last commit conforms to your wishes though this is extremely hacky imho but thtats because common-cli does not support functions that we would want like hidden options. I also removed full stack trace from error in options as its most probable cause if missing argument and then its enough to just state that. Also printed that before help menu to make it more like normal programs output.

**Pull request merged**
